version: '3.7'
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongod.conf.orig:/etc/mongod.conf.orig
    ports:
      - 27017:27017
    networks:
      - proxynet
  mongo-express:
    image: mongo-express:1.0.0-18-alpine3.18
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/
    networks:
      - proxynet
  mongo-api:
    image: openjdk:8
    container_name: mongo-api
    restart: always
    tty: true
    working_dir: /app
    links:
      - mongo
    ports:
      - 8099:8099
    volumes:
      - ./api:/app
      - ./api/elasticsearch-0.0.1-SNAPSHOT.jar:/app/app.jar
    entrypoint: /app/entrypoint.sh
    networks:
      - proxynet
networks:
  proxynet:
    name: yd_network